# Generated by Django 4.2.7 on 2024-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
